name: Build and Publish Package

on:
  release:
    types: [published]

jobs:
  Release-PyPI-Package:
    runs-on: ubuntu-latest
    permissions:
      # this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        run: pip3 install -U pip wheel "setuptools<66.0.0" setuptools_scm twine
      - name: Build distributions
        run: python setup.py sdist bdist_wheel
      - name: Check distributions
        run: twine check dist/*
      - name: Publish distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
